FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY api/ ./api/
COPY trainer/ ./trainer/
COPY model/ ./model/
COPY data/ ./data/

CMD ["uvicorn", "api.app:app", "--host", "0.0.0.0", "--port", "8000"]
